#!/bin/sh
set -eu
ROOT=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
cd "$ROOT"

for command in cargo rustc dpkg-buildpackage; do
    command -v "$command" >/dev/null 2>&1 || {
        echo "Missing build dependency: $command" >&2
        exit 1
    }
done

for command in git gh gpg; do
    command -v "$command" >/dev/null 2>&1 || {
        echo "Missing runtime dependency: $command" >&2
        exit 1
    }
done

# Keep the build reproducible. Never invoke cargo update with guessed
# transitive versions. A missing Cargo.lock is generated by Cargo itself.
if [ ! -f Cargo.lock ]; then
    cargo generate-lockfile
fi

# rustfmt is a quality check, not a build prerequisite. Debian installations
# may provide cargo without cargo-fmt. Run it when available, but do not make
# a valid build depend on an optional rustfmt component.
if cargo fmt --version >/dev/null 2>&1; then
    cargo fmt --all -- --check
else
    echo "Notice: rustfmt/cargo-fmt is not installed; skipping formatting check." >&2
fi

cargo check --locked
cargo test --locked
cargo build --release --locked

dpkg-buildpackage -us -uc -b

OUT="/tmp/ghcap-debs"
rm -rf "$OUT"
mkdir -p "$OUT"
for file in "$(dirname "$ROOT")"/ghcap_0.13.0-1_*.deb; do
    [ -f "$file" ] && cp -f "$file" "$OUT/"
done
printf '%s\n' "Built packages copied to: $OUT"
printf '%s\n' "Install with: sudo apt install $OUT/ghcap_0.13.0-1_amd64.deb"
